# Generated by Django 4.2.4 on 2023-08-15 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('composer_listing_app', '0001_initial'),
        ('list_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listening_list',
            name='listener',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='composer_listing_item',
            name='composer_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='composer_listing_app.composer_listing'),
        ),
        migrations.AddField(
            model_name='composer_listing_item',
            name='listening_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_app.listening_list'),
        ),
    ]
