# Generated by Django 4.2.4 on 2023-08-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer_name', models.CharField(max_length=128)),
                ('work_title', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
